platform :ios, '12.0' # Make sure this is uncommented and set to 12.0 or higher

# Flutter-specific lines
flutter_application_path = File.expand_path('..')
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This line automatically finds and installs all your plugins
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# This script fixes the deployment target warnings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end